name: Build app image
description: Builds app image for a given branch, tag and push it to docker hub
inputs:
  version:
    description: App version (branch) to build
    required: false
    default: main
  tag:
    description: Tag name for the resulting image
    required: false
    default: latest
  docker-hub-user:
    description: User to push image
    required: true
  docker-hub-token:
    description: Token of user
    required: true
  token:
    description: Github token
    required: true
  docker-hub-address:
    description:  Docker Hub address
    required: true
  
runs:
  using: composite
  steps:
    - name: Run Configuration
      run: |
        echo "#####################"
        echo "* Building ${{inputs.version}}"
        echo "* Push configured as: ${{inputs.push}}"
        echo "* Tag configured as: ${{inputs.tag}}"
        echo "* Docker Hub address as: ${{inputs.docker-hub-address}}"
        echo "#####################"
      shell: bash

    - name: Check for corresponding branch exists
      uses: octokit/request-action@v2.x
      id: check-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        route: GET /repos/{owner}/{repo}/branches/{branch}
        owner: AnhNg-GithubActions
        repo: app
        branch: ${{ inputs.version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/checkout@v3
      with:
        path: ./${{ inputs.version }}
        repository: AnhNg-GithubActions/app
        ref: ${{ inputs.version }}
        token: ${{secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-hub-user }}
        password: ${{ inputs.docker-hub-token }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./${{ inputs.version }}
        file: ./${{ inputs.version }}/Dockerfile
        push: true
        tags: ${{inputs.docker-hub-address}}/app:${{inputs.tag}}
